from __future__ import annotations

"""
Static Matplotlib visualization from an AnimationSpec-like JSON.

This example reads spec JSON files in `examples/out/` (generated by
`examples/06_generate_specs_for_js_demo.py`) and renders:

- n=2: segment plot (mpl2),
- n=3: ternary plot (mpl3).

Warning
-------
This example requires Matplotlib at runtime. Install with:
`pip install tucoop[viz]`.
"""

import json
from pathlib import Path
import sys
import argparse

# Ensure the examples folder (for `_bootstrap.py`) is importable even when this file is
# executed from outside `packages/tucoop-py/examples`.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _bootstrap import add_src_to_path

add_src_to_path()

from tucoop.viz.mpl2 import plot_spec_segment
from tucoop.viz.mpl3 import plot_spec_ternary


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _resolve_dir(p: str) -> Path:
    path = Path(p)
    if path.is_absolute():
        return path
    return Path(__file__).resolve().parent / path


def main() -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--spec-dir",
        default="out",
        help="Directory containing spec JSON files (absolute, or relative to this file). Default: out",
    )
    parser.add_argument(
        "--out",
        default="out",
        help="Output directory for PNGs (absolute, or relative to this file). Default: out",
    )
    args = parser.parse_args()

    spec_dir = _resolve_dir(str(args.spec_dir))
    out_dir = _resolve_dir(str(args.out))
    out_dir.mkdir(parents=True, exist_ok=True)

    # n=2
    spec2_path = spec_dir / "demo_2p.json"
    if spec2_path.exists():
        spec2 = _read_json(spec2_path)
        fig2, _ = plot_spec_segment(
            spec2,
            sets=("imputation", "core", "core_cover", "reasonable"),
            solutions=("shapley", "normalized_banzhaf"),
            compute_missing=False,
        )
        fig2.savefig(out_dir / "viz_demo_2p.png", dpi=160, bbox_inches="tight")

    # n=3
    spec3_path = spec_dir / "demo_3p.json"
    if spec3_path.exists():
        spec3 = _read_json(spec3_path)
        fig3, _ = plot_spec_ternary(
            spec3,
            sets=("imputation", "core", "core_cover", "reasonable", "weber"),
            solutions=("shapley", "normalized_banzhaf"),
            frame_index=0,
            compute_missing=False,
        )
        fig3.savefig(out_dir / "viz_demo_3p.png", dpi=160, bbox_inches="tight")

    print("== Output ==")
    print("Wrote:")
    if spec2_path.exists():
        print("-", out_dir / "viz_demo_2p.png")
    if spec3_path.exists():
        print("-", out_dir / "viz_demo_3p.png")
    if not spec2_path.exists() and not spec3_path.exists():
        print("- (no spec files found in examples/out; run examples/06_generate_specs_for_js_demo.py first)")


if __name__ == "__main__":
    try:
        main()
    except ImportError as e:
        # Most likely: matplotlib not installed (tucoop[viz]).
        raise SystemExit(str(e)) from e
